[build]
  # Directory to change to before starting build
  base = "night-sky-app"
  
  # Directory containing the deploy-ready HTML files and assets
  publish = "dist"
  
  # Default build command
  command = "npm run build"
  
  # Directory with the serverless functions
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Redirect all serverless function calls
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching (Development & Branch Deploys)
# Relaxed CSP for Vite dev server compatibility
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=()"
    # Relaxed CSP for development - allows Vite's HMR and inline scripts
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' https://models.github.ai https://*.netlify.app https://calendar.google.com https://outlook.live.com https://calendar.yahoo.com ws: wss:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Production-only headers with strict CSP
[context.production]
  [[context.production.headers]]
    for = "/*"
    [context.production.headers.values]
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=()"
      # Strict CSP for production - no 'unsafe-inline' or 'unsafe-eval'
      # Removed ws: and wss: as they're not needed in production build
      Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' https://models.github.ai https://*.netlify.app https://calendar.google.com https://outlook.live.com https://calendar.yahoo.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"
